sudo python3 -m pip install opencv-python
sudo python3 -m pip install scikit-learn
sudo python3 -m pip install numpy==1.26.4
sudo python3 -m pip install webcolors
sudo python3 -m pip install matplotlib
sudo python3 -m pip install torch
sudo python3 -m pip install Pillow
sudo python3 -m pip install transformers
sudo python3 -m pip install torchvision
sudo python3 -m pip install scipy
sudo python3 -m pip install boto3
sudo python3 -m pip install python-dateutil==2.8.1
sudo python3 -m pip install psutil
sudo python3 -m pip install pandas==1.5.3
sudo python3 -m pip install py-cpuinfo
sudo python3 -m pip install ultralytics-thop==2.0.12
sudo python3 -m pip install seaborn==0.13.2
sudo python3 -m pip install tzdata
sudo python3 -m pip install ultralytics