apiVersion: v1
kind: Service
metadata:
  name: webui-service
spec:
  selector:
    app: webui
  ports:
    - protocol: TCP
      port: 30001
      targetPort: 30001
      nodePort: 30001   # <-- Custom node port
  type: NodePort